use_frameworks!

platform :ios, '9.0'

target 'PrivateHelloWorld_Example' do
  pod 'PrivateHelloWorld', :path => '../'

  target 'PrivateHelloWorld_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
